# Generated by Django 5.0.6 on 2024-06-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megagames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
